branch-defaults:
  default:
    environment: null
global:
  application_name: Flask-Fun
  branch: null
  default_ec2_keyname: eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: devpd
  repository: null
  sc: null
  workspace_type: Application
